[workers]
worker-1 ansible_host=<worker-1-private-ip> ansible_user=ec2-user
worker-2 ansible_host=<worker-2-private-ip> ansible_user=ec2-user

[workers:vars]
ansible_ssh_private_key_file=~/.ssh/ansible-ec2-key
ansible_python_interpreter=/usr/bin/python3